project:
  type: website
  output-dir: docs

knitr:
  opts_chunk: 
    collapse: true

website:
  title: "Fabian Rosenthal"
  favicon: "images/profile.png"
  navbar:
    left:
      - href: index.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
    right:
      - about.qmd
      - icon: github
        href: https://github.com/radlfabs
      - icon: linkedin
        href: https://www.linkedin.com/in/fabian-rosenthal-mle
  page-footer:
    center: |
      [Contact Fabian Rosenthal](mailto:rosenthal.fabian@gmail.com)

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true



